[package]
name = "zksync_os_runner"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
airbender-host = { workspace = true }
cycle_marker = { path = "../cycle_marker", optional = true }

[features]
cycle_marker = ["dep:cycle_marker", "cycle_marker/use_riscv_transpiler"]
flamegraph = []
