[package]
name = "multiblock_batch_tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rig = { path = "../../rig", features = ["for_tests"] }
zksync_os_runner = { path = "../../../zksync_os_runner"}
hex = { workspace = true }

[features]
e2e_proving = ["rig/e2e_proving"]
cycle_marker = ["rig/cycle_marker"]
