[package]
name = "eth_runner"
version = "0.1.0"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-os/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync", "zk", "risc-v"]
categories = ["cryptography"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ruint = { version = "1.16", default-features = false }

alloy = { version = "1", features = ["full", "ssz"]}
serde_json = { version = "1.0", features = ["unbounded_depth"] }
rig = { path = "../../rig", features = ["eth_runner"]}
zk_ee = { path = "../../../zk_ee" }
basic_system = { path = "../../../basic_system" }
clap = { version = "4.4", features = ["derive"] }
anyhow = "=1.0.89"
ureq = { version = "3", features = ["json", "gzip"] }
sled = {version = "0.34" }
bincode = { version = "2", features = ["serde"] }
alloy-rpc-types-debug = { version = "*", default-features = false }
csv = "1.3"
reqwest = { version = "0.12", features = ["json", "blocking", "rustls-tls"] }
zstd = "0.13"

airbender-host = { git = "https://github.com/matter-labs/airbender-platform", rev = "ff643be8", default-features = false }

[features]
proving = []
gpu = ["airbender-host/gpu-prover"]
default = []

