[package]
name = "rig"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
basic_bootloader = { path = "../../basic_bootloader" }
basic_system = { path = "../../basic_system" }
evm_interpreter = { path = "../../evm_interpreter" }
forward_system = { path = "../../forward_system" }
oracle_provider = { path = "../../oracle_provider" }
callable_oracles = { path = "../../callable_oracles/" }
zk_ee = { path = "../../zk_ee" }
zksync_os_runner = { path = "../../zksync_os_runner"}
system_hooks = { path = "../../system_hooks"}
crypto = { path = "../../crypto" }
cycle_marker = { path = "../../cycle_marker", optional = true }
zksync_os_api = { path = "../../api" }
zksync_os_interface = { workspace = true }
cli = { workspace =  true, optional = true }
airbender-host = { workspace = true, optional = true }
gpu_prover = { workspace = true, optional = true }

zksync_os_tests_common = { path = "../common" }
zksync_os_revm_runner = { path = "../revm_runner" }

ruint = { workspace = true, default-features = false }
env_logger = { workspace = true }
log = { workspace = true }
alloy = { workspace = true, features = ["full", "eip712", "consensus"] }
alloy-rlp = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-rpc-types-debug = { workspace = true }
once_cell = { workspace = true }

[features]
default = ["testing"]
testing = []
airbender_cli = ["cli"]
e2e_proving = ["airbender-host"]
no_print = ["forward_system/no_print"]
cycle_marker = ["dep:cycle_marker", "zksync_os_runner/cycle_marker", "zk_ee/cycle_marker", "evm_interpreter/cycle_marker", "basic_system/cycle_marker", "basic_bootloader/cycle_marker"]
unlimited_native = ["forward_system/unlimited_native"]
gpu = ["cli/gpu", "gpu_prover"]
production = ["forward_system/production"]
# Features for test instances
for_tests = ["forward_system/for_tests"]
# Features used for eth_runner
eth_runner = ["forward_system/eth_runner"]
eth_stf = ["forward_system/eth_stf"]
# Features used for evm_tester
evm_tester = ["forward_system/evm_tester"]
# Features used for legacy evm_tester. Only defined in forward system,
# as the legacy evm_tester does not perform a proof run.
evm_tester_legacy = ["forward_system/evm_tester_legacy"]
