[package]
name = "basic_system_proving"
resolver = "2"
version = "0.1.0"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-os/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync", "zk", "risc-v"]
categories = ["cryptography"]

[lib]
path = "../../../../../basic_system/src/lib.rs"

[dependencies]
zk_ee = { package = "zk_ee_proving", path = "../zk_ee_proving", default-features = false }
u256 = { path = "../../../../../supporting_crates/u256", default-features = false }
evm_interpreter = { package = "evm_interpreter_proving", path = "../evm_interpreter_proving"  }
ruint = { version = "1.12.3", default-features = false, features = ["alloc"] }
crypto = { package = "crypto_proving", path = "../crypto_proving", default-features = false, features = ["secp256k1-static-context"]}
arrayvec = { version = "0.7.4", default-features = false }
either = { version = "*", default-features = false }
storage_models = { package = "storage_models_proving", path = "../storage_models_proving", default-features = false }
modexp = { path = "../../../../../supporting_crates/modexp" }
cycle_marker = { path = "../../../../../cycle_marker" }
num-bigint = { version =  "*", optional = true}
num-traits = { version =  "*", optional = true}
cc-traits = { path = "../../../../../basic_system/src/system_implementation/ethereum_storage_model/supporting_crates/cc-traits" }
const-hex = { version = "1", default-features = false }

rand = {version = "0.9.0", optional = true}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"], optional = true }
strum_macros = "0.27.1"
paste = "1.0.15"

[features]
testing = ["zk_ee/testing", "evm_interpreter/testing", "serde", "ruint/serde", "rand", "crypto/testing", "num-bigint", "num-traits"]
evm-compatibility = []
default = ["testing"]
cycle_marker = ["cycle_marker/log_to_file"]
wrap-in-batch = []
proving = ["crypto/proving"]
evm_refunds = ["storage_models/evm_refunds"]
# The finish method will just return inputs, so outputs can be procesed outside bootloader
# Used for proving multi block batch within 1 run
multiblock-batch = []
state-diffs-pi = []

[dev-dependencies]
hex = {version = "0.4.3"}
proptest = "1.6.0"
crypto = { package = "crypto_proving", path = "../crypto_proving", default-features = false, features = ["secp256k1-static-context", "testing"]}
num-bigint = "*"
num-traits = "*"
arbitrary = { version = "1", features = ["derive"] }
serde_json = "*"
alloy-rpc-types-debug = { version = "=1.7.3", default-features = false }
alloy = { version = "=1.7.3", features = ["rlp", "full"] }
alloy-rlp = { version = "*" }
alloy-primitives = { version = "1", features = ["arbitrary"] }
reqwest = { version = "*", features = ["blocking", "json"] }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.8.4" }
reth-trie-sparse = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.8.4" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(fuzzing)"] }
