# This workflow just builds the fuzz targets without running them.
name: Daily Fuzz Build

on:
    schedule:
        - cron: "0 1 * * *"

permissions: read-all

env:
    ZKSYNC_RISC_V_RUN: true
    CI: true
    ZKSYNC_USE_CUDA_STUBS: true

jobs:
    build-fuzz-targets:
        name: Build fuzz targets
        runs-on: [matterlabs-ci-runner]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: clippy, rustfmt
                  rustflags: ""

            - name: Setup
              run: |
                  rustup set profile minimal
                  rustup component add rust-src

            - name: Install cargo-airbender
              run: cargo install cargo-airbender --git https://github.com/matter-labs/airbender-platform --locked

            - name: Compile for RISC-V
              working-directory: ./zksync_os
              run: ./dump_bin.sh --type for-tests

            - name: Compile for forward running
              run: cargo build --release

            - name: Install cargo-fuzz
              run: cargo install cargo-fuzz

            - name: Build fuzz tests
              run: |
                  cd tests/fuzzer
                  cargo fuzz build -D

            - name: Run regression tests
              run: |
                  cd tests/fuzzer
                  ./fuzz.sh regression

            - name: Run smoke fuzz tests
              run: |
                  cd tests/fuzzer
                  ./fuzz.sh smoke
